---
spring:
  profiles: client1
  application:
    name: eureka-client
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: client2
  application:
    name: eureka-client
server:
  port: 8763
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/