spring:
  application:
    name: service-zuul
server:
  port: 5000
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      # 值自定义
      serviceid: hiapi-v1
hiapi-v1:
  ribbon:
    listOfServers: http://localhost:8762,http://localhost:8763
ribbon:
  eureka:
    enabled: false