spring:
  application:
    name: service-zuul
server:
  port: 5000
zuul:
  routes:
    # 配置eureka-client转发
    hiapi:
      path: /hiapi/**
      serviceid: eureka-client
    feignapi:
      # 配置eureka-feign-client转发
      path: /feignapi/**
      serviceid: eureka-feign-client